Repository LLNL/hatchet, pull requests merged in 2024-06, with the labels that each got.

#132 Hotfix: upgrades versions for GitHub Actions
  .github/workflows/build_and_upload_wheels.yaml
  .github/workflows/pip-install-tester.yaml
  .github/workflows/unit-tests.yaml
Labels: area-ci, area-deployment, priority-urgent, status-ready-for-review, type-bug

#135 Updates version to 2024.1.2
  hatchet/version.py
  pyproject.toml
Labels: area-deployment, priority-normal, status-ready-for-review, type-release

#136 Adds test for upload-artifact@v4
  .github/workflows/build_and_upload_wheels.yaml
Labels: area-deployment, priority-urgent, status-ready-for-review, type-bug

#137 Fixes minor typo that will cause CD to fail
  .github/workflows/build_and_upload_wheels.yaml
Labels: area-deployment, priority-urgent, status-work-in-progress, type-bug

#138 Apply Unit Test Change from Thicket
  hatchet/tests/caliper.py
Labels: area-tests, priority-normal, status-ready-for-review
